apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-database
  name: test-database
spec:
  containers:
  - image: 760240387743.dkr.ecr.eu-central-1.amazonaws.com/test:database
    name: test-database
      envFrom:
      - configMapRef:
          name: config
